# Optional: the project deploys to Vercel by default, where this file is unused.
# It exists so a project scaffolded from this template can self-host without
# re-deriving the build.
#
#   docker build -t starter-kit .
#   docker run --rm -p 3000:3000 starter-kit
#
# Requires `output: 'standalone'`, which next.config.ts enables via DOCKER_BUILD.

# Pinned to the major in .nvmrc.
ARG NODE_VERSION=24-alpine

# ---- deps ------------------------------------------------------------------
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

RUN corepack enable

# Copy only the manifests first so the install layer caches across code changes.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

# ---- build -----------------------------------------------------------------
FROM node:${NODE_VERSION} AS builder
WORKDIR /app

RUN corepack enable

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public env vars are inlined at build time, so anything the browser needs must
# be present here — passing it at `docker run` is too late.
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

ENV DOCKER_BUILD=1
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm build

# ---- runner ----------------------------------------------------------------
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# The standalone bundle deliberately excludes `public/` and `.next/static`,
# so both are copied explicitly.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by the standalone build; there is no `next start` here.
CMD ["node", "server.js"]
